import { beforeEachMedication, generateRandomGuid } from "../../fixtures/beforeEach";
import { beforeEach, feature } from "@emisgroup/xgp-playwright-boilerplate";
import { CancelMedicationPanelActions } from "../../actions/cancel-medication-panel-actions";
import { CommonActions } from "../../actions/common-actions";
import { test } from "../../fixtures/test";
import { CancelMedicationPage } from "../../pages/cancel-medication-page";

test.describe("Cancel single issued drug", () => {
    test.beforeEach(beforeEach);
    test.beforeEach(beforeEachMedication);
    let randomGuid: string;
    test.beforeEach(() => {
        randomGuid = generateRandomGuid();
    });
    test.beforeEach(async () => {
        await feature(
            "[1] Cancel Single Medication EPS UI (NOT Downloaded by Pharmacy) (XS)",
            "EMISXGP-689",
            "https://emisgroup.aha.io/features/EMISXGP-689"
        );
    });

    test("Validate the single cancel issue panel for the eps flow - success scenaio", { tag: ["@CIS2", "@US450490", "@US462523"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "fullsuccess");
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
        await cancelMedicationPanelActions.clickCancelAdditionalInformationInputField();
        await cancelMedicationPanelActions.verifyInputFieldAcceptsOnly30CharactersAndSpecialCharacters();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(1);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
    });

    test("Validate the single cancel issue panel for the eps flow - Retriable failure", { tag: ["@CIS2", "@US450490", "@US474815"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "fullfailure_at_emisapi_retriable");
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Technical error", "Try cancelling again.");
        await cancelMedicationPanelActions.clickTryAgainButton();
        await cancelMedicationPanelActions.validateSpinnerAndSkeletonOnTryAgainClick();
        // await cancelMedicationPanelActions.verifyTheCancellationErrorBanner();
    });

    test("Validate the single cancel issue panel for the eps flow - Non retriable failure", { tag: ["@CIS2", "@US450490", "@US474815"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "fullfailure_at_emisapi_nonretriable");
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Technical error", "");
        await cancelMedicationPanelActions.validateTheTryagainButtonIsNotVisible();
        // await cancelMedicationPanelActions.verifyTheCancellationErrorBanner();
    });

    test("Validate Cancel issue option is enabled for EPS issued medications through CIS2 login", { tag: ["@CIS2", "@462181"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
    });

    test("Validate the error dialogue box for R-0005 error code", { tag: ["@CIS2", "@US430000", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0005");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Aspirin 75mg tablets", todayDate, "Expired", "");
        // await cancelMedicationPanelActions.verifyErrorDialogBoxForR_0005ErrorCode();
        // await cancelMedicationPanelActions.verifyTheColourOfTheElement(cancelMedication.cancelMedicationErrorDialogBoxCloseButton, "#3a76ba", "--button-background");
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxIsClosed();
    });

    test("Validate notification when user try to cancel a medication downloaded by the pharmacy(R-0002)", { tag: ["@CIS2", "@458852", "@US466335", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, cancelMedicationPanelActions, commonActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0002");
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "With dispenser", "Contact the dispenser.");
        // await cancelMedicationPanelActions.verifyDownloadedByPharmacyErrorDialog("Co-cyprindiol 2000microgram", randomGuid, "12");
    });

    test("Validate the error dialogue box for R-0004 error code", { tag: ["@CIS2", "@US454402", "@US466335", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0004");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Aspirin 75mg tablets", todayDate, "Dispensed to patient", "Contact the dispenser/patient.");
        // await cancelMedicationPanelActions.verifyErrorDialogBoxForR_0004ErrorCode("Aspirin 75mg tablets", randomGuid, "12");
        // await cancelMedicationPanelActions.verifyTheColourOfTheElement(cancelMedication.cancelMedicationErrorDialogBoxCloseButton, "#dc3546", "--button-background");
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxIsClosed();
    });

    test("Validate notification when user try to cancel a medication downloaded by the pharmacy and in active state to dispense(R-0003)", { tag: ["@CIS2", "@458917", "@US466335", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, cancelMedicationPanelActions, commonActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0003");
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "With dispenser", "Contact the dispenser.");
        // await cancelMedicationPanelActions.verifyDownloadedByPharmacyAndDispenseActiveErrorDialog("Co-cyprindiol 2000microgram", randomGuid, "12");
    })

    test("Validate the error dialogue box for R-0008 error code", { tag: ["@CIS2", "@US450486", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0008");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Aspirin 75mg tablets", todayDate, "Technical error", "Try cancelling again.");
        // const todayDate = await commonActions.getTodayDate();
        // await cancelMedicationPanelActions.verifyErrorDialogBoxForR_0008ErrorCode("Aspirin 75mg tablets", todayDate);
    });
    test("Validate notification when user try to cancel a medication and system encounters an error from the Spine[API Error-Non Retryable]", { tag: ["@CIS2", "@461131", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, cancelMedicationPanelActions, commonActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "400");
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Technical error", "Contact the patient.");
        // await cancelMedicationPanelActions.verifySpineNonRetryableErrorDialog("Co-cyprindiol 2000microgram", randomGuid, "12");
    });

    test("Validate the error dialogue box for R-5000 error code", { tag: ["@CIS2", "@US450488", "@US466335", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-5000");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Aspirin 75mg tablets", todayDate, "Technical error", "Contact the dispenser/patient.");
        // await cancelMedicationPanelActions.verifyErrorDialogBoxForR_5000_0099_5006And5888ErrorCodes("Aspirin 75mg tablets", randomGuid, "12");
        // await cancelMedicationPanelActions.verifyTheErrorDialogBoxIsClosed();
    });

    test("Validate the error dialogue box for 0099 error code", { tag: ["@CIS2", "@US450488", "@US466335", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0099");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Aspirin 75mg tablets", todayDate, "Technical error", "Contact the dispenser/patient.");
        // await cancelMedicationPanelActions.verifyErrorDialogBoxForR_5000_0099_5006And5888ErrorCodes("Aspirin 75mg tablets", randomGuid, "12");
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxIsClosed();
    });

    test("Validate the error dialogue box for 5006 error code", { tag: ["@CIS2", "@US450488", "@US466335", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-5006");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Aspirin 75mg tablets", todayDate, "Technical error", "Contact the dispenser/patient.");
        // await cancelMedicationPanelActions.verifyErrorDialogBoxForR_5000_0099_5006And5888ErrorCodes("Aspirin 75mg tablets", randomGuid, "12");
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxIsClosed();
    });

    test("Validate the error dialogue box for 5888 error code", { tag: ["@CIS2", "@US450488", "@US466335", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-5888");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Aspirin 75mg tablets", todayDate, "Technical error", "Contact the dispenser/patient.");
        // await cancelMedicationPanelActions.verifyErrorDialogBoxForR_5000_0099_5006And5888ErrorCodes("Aspirin 75mg tablets", randomGuid, "12");
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxIsClosed();
    });

    test("Validate notification when user try to cancel a medication has already been cancelled and the app has not updated(R-0006)", { tag: ["@CIS2", "@450485", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, cancelMedicationPanelActions, commonActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0006");
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Already cancelled", "");
        // await cancelMedicationPanelActions.verifyAlreadyCancelledErrorDialog("Co-cyprindiol 2000microgram", randomGuid, "12");
    });

    test("Validate the error dialogue box for R-0007 error code", { tag: ["@CIS2", "@US454401", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0007");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Aspirin 75mg tablets", todayDate, "Pending", "Cancellation already requested. Either wait or contact the dispenser yourself.");
        // await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_0007ErrorCode("Aspirin 75mg tablets", "12", "12");
    });

    test("Validate the error dialogue box for R-0009 error code", { tag: ["@CIS2", "@US452362", "@US466335", "@US474815"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0009");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Aspirin 75mg tablets", todayDate, "Technical error", "Try cancelling again.");
        await cancelMedicationPanelActions.clickTryAgainButton();
        await cancelMedicationPanelActions.validateSpinnerAndSkeletonOnTryAgainClick();
        // await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_0009ErrorCode("Aspirin 75mg tablets", "12", "12");
    });
    test("Validate the EPS error tracker link is redirected to required URL while clicking on it", { tag: ["@CIS2", "@US466335"] }, async ({ issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions, cancelMedication }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Aspirin 75mg tablets " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0009");
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Aspirin 75mg tablets");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await commonActions.validateTheUrlAfterClickingOnTheLink(cancelMedication.epsPrescriptionErrorTrackerLink, "https://portal2.national.ncrs.nhs.uk/prescriptionsadmin/");
    });

    test("Verify that the error dialog box displays the 'With dispenser' tag and the message 'Contact the dispenser / patient.' for R-0002 and R-0003 error codes", { tag: ["@US463700"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0002|R-0003|R-0002|R-0003");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_0002AndR_0003ErrorCodes_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
    });

    test("Verify that the error dialog box displays the 'Dispensed to patient' tag and the message 'Contact the dispenser / patient.' for the R-0004 error code.", { tag: ["@US463700"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0004|R-0004|R-0004|R-0004");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_0004ErrorCode_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
    });

    test("Verify whether the error dialog box is displayed with 'Technical error' tag 'Try cancelling again.' text and 'Try again' button for R-0008, R-0009 or 'X scenario' error code", { tag: ["@US463700"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0008|R-0008|R-0008|504");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_0008AndR0009ErrorCodes_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
    });

    test("Verify whether the error dialog box is displayed with 'Technical error' tag, 'Contact the dispenser/patient.' text when medications cancellation failed with R-5000, R-0099, R-5006, R-5888, non-EPS Non-retriable error codes", { tag: ["@US463700"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-5000|R-0099|R-5006|400");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_5000_0099_5006And5888ErrorCodes_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
    });

    test("Verify whether the error dialog box is displayed with 'Pending' tag 'Cancellation already requested. Either wait or contact the dispenser yourself.' text when several medications cancellation failed with R-0007 error code", { tag: ["@US463700"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0007|R-0007|R-0007|R-0007");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_0007ErrorCode_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
    });

    test("Verify whether the error dialog box is displayed with 'Already cancelled' tag when several medications cancellation failed with R-0006 error code", { tag: ["@US463700"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 300mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0006|R-0006|R-0006|R-0006");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_0006ErrorCode_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
    });

    test("Verify whether the error dialog box is displayed with 'Expired' tag when several medications cancellation failed with R-0005 error code", { tag: ["@US463700"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0005|R-0005|R-0005|R-0005");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_0005ErrorCode_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
    });

    test("Verify whether the error dialog box is displayed with 'Not dispensed' tag when several medications cancellation failed with R-0010 error code", { tag: ["@US463700"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0010|R-0010|R-0010|R-0010");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForR_0010ErrorCode_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
    });

    test("Verify visibility of 'Cancellation rejection tasks have been created in EMIS Web Workflow Manager.' text in error dialog for multiple medication cancellations across various scenarios", { tag: ["@US475191"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-00002|R-0003|R-0002|R-0003");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyWorkflowTasksCreatedTextIsVisible_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-00002|R-0003|400|500");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyWorkflowTasksCreatedTextIsVisible_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "504|501|400|500");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyWorkflowTasksCreatedTextIsNotVisible_multipleCancellation(4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(4);
    });

    test("Verify whether the success notification is displayed when cancelling single eps issued medication", { tag: ["@US462523"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 1);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "fullsuccess");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(1);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "");
    });

    test("Verify whether the success notification is displayed when cancelling multiple eps issued medications", { tag: ["@US462523"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "fullsuccess");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(4);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "");
    });

    test("Verify universal dialog displays correct text for all error codes during single medication cancellation via cancel issue button", { tag: ["@US474815"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 1);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "400");
        await cancelMedicationPanelActions.clickCancelIssueButton();
        const todayDate = await commonActions.getTodayDate();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Technical error", "Contact the patient.");
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "504");
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Technical error", "Try cancelling again.");
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0002");
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "With dispenser", "Contact the dispenser.");
        await cancelMedicationPanelActions.verifyWorkflowTaskCreatedTextIsVisible_singleCancellation();
        await cancelMedicationPanelActions.verifyTheDispenserDetails();
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0004");
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Dispensed to patient", "Contact the dispenser/patient.");
        await cancelMedicationPanelActions.verifyWorkflowTaskCreatedTextIsVisible_singleCancellation();
        await cancelMedicationPanelActions.verifyTheDispenserDetails();
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0008");
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Technical error", "Try cancelling again.");
        await cancelMedicationPanelActions.clickTryAgainButton();
        await cancelMedicationPanelActions.validateSpinnerAndSkeletonOnTryAgainClick();
        await cancelMedicationPanelActions.verifyWorkflowTaskCreatedTextIsVisible_singleCancellation();
        await cancelMedicationPanelActions.verifyTheDispenserDetails();
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-5000");
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Technical error", "Contact the dispenser/patient.");
        await cancelMedicationPanelActions.verifyWorkflowTaskCreatedTextIsVisible_singleCancellation();
        await cancelMedicationPanelActions.verifyTheDispenserDetails();
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0007");
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Pending", "Cancellation already requested. Either wait or contact the dispenser yourself.");
        await cancelMedicationPanelActions.verifyWorkflowTaskCreatedTextIsVisible_singleCancellation();
        await cancelMedicationPanelActions.verifyTheDispenserDetails();
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0006");
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Already cancelled", "");
        await cancelMedicationPanelActions.verifyWorkflowTaskCreatedTextIsVisible_singleCancellation();
        await cancelMedicationPanelActions.verifyTheDispenserDetails();
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0005");
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Expired", "");
        await cancelMedicationPanelActions.verifyWorkflowTaskCreatedTextIsVisible_singleCancellation();
        await cancelMedicationPanelActions.verifyTheDispenserDetails();
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "R-0010");
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySingleCancellationUniversalErrorDialogBox("Co-cyprindiol 2000microgram", todayDate, "Not dispensed", "");
        await cancelMedicationPanelActions.verifyWorkflowTaskCreatedTextIsVisible_singleCancellation();
        await cancelMedicationPanelActions.verifyTheDispenserDetails();
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
    });

    test("Validate Cancel issue option is enabled for RD where the last issue method is Electronic through CIS2 login", { tag: ["@CIS2", "@477078"] }, async ({ commonActions, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, cancelMedicationPanelActions }) => {
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatDispensingMedication("Co-cyprindiol 2000microgram", randomGuid, "6", "6", "2", "RD");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsEnabled();
        await medicationHomeActions.SelectSingleDrugCheckbox(1);
        await medicationHomeActions.verifymsmToolBarMoreOptionsCancelIssueDropdownState("enabled");
        await commonActions.updateScreenSize(350, 900);
        await medicationHomeActions.clickToolBarMoreOptionsMenu();
        await medicationHomeActions.verifymsmToolBarMoreOptionsCancelIssueDropdownState("enabled");
    });
    
}); 