import { beforeEachMedication, generateRandomGuid } from "../../fixtures/beforeEach";
import { beforeEach } from "@emisgroup/xgp-playwright-boilerplate";
import { CancelMedicationPanelActions } from "../../actions/cancel-medication-panel-actions";
import { test } from "../../fixtures/test";

test.describe("Cancel issued drug", () => {
    test.beforeEach(beforeEach);
    test.beforeEach(beforeEachMedication);
    let randomGuid: string;
    test.beforeEach(() => {
        randomGuid = generateRandomGuid();
    });

    test("Validate additional field in cancel issue dialog", { tag: ["@US450491"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "fullsuccess");
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
        await cancelMedicationPanelActions.clickCancelAdditionalInformationInputField();
        await cancelMedicationPanelActions.verifyInputFieldAcceptsOnly30CharactersAndSpecialCharacters();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
    });

    test("Validate Cancel issue option is not enabled for EPS issued medications through non CIS2 login", { tag: ["@462181"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.verifyCancelLatestIssueIsNotEnabled();
    });

    test("Validate the single cancel issue panel", { tag: ["@US462186"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
    });

    test("Validate the error banner for retryable errors", { tag: ["@US450493"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await cancelMedicationPanelActions.clickFirstKebabMenu();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "fullfailure_at_emisapi_retriable");
        await cancelMedicationPanelActions.clickCancelIssueOption();
        await cancelMedicationPanelActions.verifyCancelIssuePanel("Co-cyprindiol 2000microgram");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButtonAndValidateTheSpinnerForRetryableError();
        await cancelMedicationPanelActions.verifyTheErrorBannerForRetriableErrorBanner("Co-cyprindiol 2000microgram");
    });

    test("Verify the error dialog box for cancel multiple medications with all failed retriable errors", { tag: ["@US462986"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "504|504|504|504");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyErrorDialogBox_AllFailedRetryable_cancelMultipleMedication(4);
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "400|400|400|400");
        await cancelMedicationPanelActions.clickTryAgainButton();
        await cancelMedicationPanelActions.validateTheTryagainButtonIsNotVisible();
    });

    test("Verify the error dialog box for cancel multiple medications with all failed non retriable errors", { tag: ["@US471156"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "400|400|400|400");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Co-cyprindiol 2000microgram/35microgram tablets" + randomGuid);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Aspirin 75mg tablets" + randomGuid);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Paracetamol 500mg tablets" + randomGuid);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Paracetamol 500mg capsules" + randomGuid);
        await cancelMedicationPanelActions.verifyErrorDialogBox_AllFailedNonRetryable_cancelMultipleMedication(4);
        await cancelMedicationPanelActions.validateTableScrollbarIsVisible();
    });

    test("Verify all already cancelled non EPS medication error banner", { tag: ["@US462180"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 300mg dispersible tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg dispersible tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyAllAlreadyCancelledNonEPSMedicationError(4);
    });

    test("Verify some already cancelled non EPS medication error banner", { tag: ["@US462180", "@regression"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 300mg dispersible tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addRepeatMedication("Aspirin 75mg dispersible tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test", "Patient contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 3);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifySomeAlreadyCancelledNonEPSMedicationError(3);
    });

    test("Verify whether the cancel medication panel is closed and a toast notification is displayed with the required text when all the items receive a success response.", { tag: ["@US471155", "@regression"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(4);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication("Co-cyprindiol 2000microgram " + randomGuid);
        await medicationHomeActions.validateEachColumnInFirstRowOfCurrentMedication(3, ["Not issued"]);
    });

    test("Verify the error dialog box for partial success and partial non-retriable failure when canceling multiple medications", { tag: ["@US471155", "@regression"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "200|200|400|400");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyErrorDialogBox_PatialSuccess_NonRetriable_cancelMultipleMedication(2, 4);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(2);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
    });

    test("Verify the error dialog box for partial success and partial retriable failure when canceling multiple medications", { tag: ["@US471155"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "200|200|504|504");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForPartialSuccessAndRetriableError(2, 4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(2);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Paracetamol 500mg tablets" + randomGuid);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Paracetamol 500mg capsules" + randomGuid);
        await cancelMedicationPanelActions.clickTryAgainButton();
        await cancelMedicationPanelActions.validateSpinnerAndSkeletonOnTryAgainClick();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(4);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
    });

    test("Verify error dialog for mixed success, retriable, and already canceled errors during multiple cancellations", { tag: ["@US471155", "@regression"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "already_cancelled|200|504|504");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForPartialSuccess_RetriableError_alreadyCancelled(3, 4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(3);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Paracetamol 500mg tablets" + randomGuid);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Aspirin 75mg tablets" + randomGuid);
        await cancelMedicationPanelActions.clickTryAgainButton();
        await cancelMedicationPanelActions.validateSpinnerAndSkeletonOnTryAgainClick();
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(1);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
    });

    test("Verify error dialog for mixed success, non retriable, and already canceled errors during multiple cancellations", { tag: ["@US471155"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "already_cancelled|400|200|400");
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForPartialSuccess_NonRetriableError_alreadyCancelled(3, 4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(3);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Co-cyprindiol 2000microgram/35microgram tablets" + randomGuid);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Aspirin 75mg tablets" + randomGuid);
        await cancelMedicationPanelActions.verifyTheMedicationListedInThePendingCancellationMedicationTable("Paracetamol 500mg tablets" + randomGuid);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(1);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "");
    });

    test("Verify error dialog for mixed success and already canceled errors during multiple cancellations", { tag: ["@US471155", "@regression"] }, async ({ page, issueMedicationPanelActions, addMedicationPanelActions, medicationHomeActions, commonActions }) => {
        const cancelMedicationPanelActions = new CancelMedicationPanelActions(page);
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Co-cyprindiol 2000microgram", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 75mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Paracetamol 500mg capsules", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickPrescribeButton();
        await addMedicationPanelActions.addAcuteMedication("Aspirin 300mg tablets", randomGuid, "12", "12", "12", "Pharmacy contraceptive Test");
        await issueMedicationPanelActions.issueMedication();
        await medicationHomeActions.clickMedsRefreshButton();
        await medicationHomeActions.searchCurrentMedication(randomGuid);
        await medicationHomeActions.SelectMultipleCheckbox(1, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(4);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
        await medicationHomeActions.UnselectMultipleCheckbox(1, 4);
        await medicationHomeActions.SelectMultipleCheckbox(2, 4);
        await cancelMedicationPanelActions.clickCancelIssueIcon();
        await cancelMedicationPanelActions.selectPrescribingErrorCancellationReason();
        await cancelMedicationPanelActions.clickCancelIssueButton();
        await cancelMedicationPanelActions.verifyTheErrorDialogBoxForPartialSuccess_And_alreadyCancelled(3, 4);
        await cancelMedicationPanelActions.verifyPendingCancellationMedicationCount(3);
        await cancelMedicationPanelActions.clickTheErrorDialogBoxCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelIssuePanelIsClosed();
        await cancelMedicationPanelActions.verifyCancellationToastNotification(1);
        await medicationHomeActions.clickToastNotificationCloseButton();
        await cancelMedicationPanelActions.verifyTheCancelNotificationPanelIsClosed();
        await commonActions.setLocalStorage("cancellatestissue_mock_scenario", "");
    });
});